## Demonstração - Pytorch

### Tensors

In [1]:
import torch
import numpy as np

#Inicialização diretamente com dados - tipo inferido automaticamente
data = [[1, 2],[3, 4]]

x_data = torch.tensor(data)
print(x_data)

#Inicialização de um NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(x_np)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [4]:
#Cria tensor com shape específico e com valores 1.
#Shape (2, 3)
ones_tensor = torch.ones(2,3)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [2]:
#Cria tensor com shape específico e com valores 0.
#Shape (3, 5)
zeros_tensor = torch.zeros(3,5)
zeros_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [5]:
#concatenação de tensors
torch.cat([ones_tensor, ones_tensor], dim=1)


tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [6]:
#multiplicação de tensors

ones_tensor * 2

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [7]:
# Cria tensor com shape específico e com valores aleaórios.

#Shape (10, 3)
x = torch.randn(10, 3)
print(x)

#Shape(10, 2)
y = torch.randn(10, 2)
print(y)


tensor([[ 2.3293, -0.4395,  1.4051],
        [-1.1878, -0.7769,  0.9488],
        [-0.0221, -0.7221, -0.1790],
        [-0.1695,  0.1977, -0.6961],
        [-0.8274,  0.2810, -0.4583],
        [-0.2433,  0.6065,  0.0471],
        [ 0.1717, -0.6669, -1.4048],
        [-0.2413,  0.0860,  0.4311],
        [ 0.2447,  0.7936, -0.0520],
        [ 0.3417, -1.9973,  1.4129]])
tensor([[ 1.4347, -0.9051],
        [-0.6299,  1.8178],
        [-0.5354,  0.6717],
        [ 1.5781, -0.4787],
        [ 0.7926, -1.5036],
        [ 0.3670,  0.8423],
        [-1.2824, -0.8437],
        [ 0.5923,  1.0103],
        [-0.2068, -0.2170],
        [ 1.6224,  0.1875]])


In [8]:
#Atributos de um tensor

print(f"Shape do tensor: {x.shape}")
print(f"Datatype do tensor: {x.dtype}")
print(f"Dispositivo onde o tensor está armazenado: {x.device}")

Shape do tensor: torch.Size([10, 3])
Datatype do tensor: torch.float32
Dispositivo onde o tensor está armazenado: cpu


In [9]:
# Movendo o tensor para a GPU se disponível 
if torch.cuda.is_available():
    x = x.to('cuda')
    
print(f"Dispositivo onde o tensor está armazenado: {x.device}")

Dispositivo onde o tensor está armazenado: cuda:0


### Manipulação de tensor 

As operações são similares a um Np-array


In [10]:
print(x)
print()
print('Primeira linha: ', x[0,:])
print('Primeira coluna: ', x[:, 0])
print('Ultima coluna:', x[:, -1])


tensor([[ 2.3293, -0.4395,  1.4051],
        [-1.1878, -0.7769,  0.9488],
        [-0.0221, -0.7221, -0.1790],
        [-0.1695,  0.1977, -0.6961],
        [-0.8274,  0.2810, -0.4583],
        [-0.2433,  0.6065,  0.0471],
        [ 0.1717, -0.6669, -1.4048],
        [-0.2413,  0.0860,  0.4311],
        [ 0.2447,  0.7936, -0.0520],
        [ 0.3417, -1.9973,  1.4129]], device='cuda:0')

Primeira linha:  tensor([ 2.3293, -0.4395,  1.4051], device='cuda:0')
Primeira coluna:  tensor([ 2.3293, -1.1878, -0.0221, -0.1695, -0.8274, -0.2433,  0.1717, -0.2413,
         0.2447,  0.3417], device='cuda:0')
Ultima coluna: tensor([ 1.4051,  0.9488, -0.1790, -0.6961, -0.4583,  0.0471, -1.4048,  0.4311,
        -0.0520,  1.4129], device='cuda:0')


# Criando modelos

## Primeiro modelo

Aqui é apresentado um exemplo simples que utiliza uma camada completamente conectada.

Para acelerar as operações na rede neural, nós a movemos para a GPU, se disponível.

In [18]:
from torch import nn
import torch.nn.functional as F

# Construi uma camada fully connected
#torch.nn.Linear(in_features, out_features, bias=True, device=None, dtype=None)
linear = nn.Linear(3, 2)

print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[-0.4498,  0.3692, -0.4609],
        [-0.0666,  0.4990,  0.1641]], requires_grad=True)
b:  Parameter containing:
tensor([0.0682, 0.2553], requires_grad=True)


In [11]:
# Pega a GPU ou CPU para treinamento.
device = "cuda" if torch.cuda.is_available() else "cpu"

print("Usando {}".format(device))

Usando cuda


In [19]:
linear = linear.to(device)

x = x.to(device)

#Operação - Forward.
pred = linear(x)
pred

#x, tensor criado acima, representa as features de entrada
#y, tensor criado acima, representa os valores alvo

tensor([[-1.7893,  0.1114],
        [-0.1216,  0.1024],
        [-0.1060, -0.1330],
        [ 0.5382,  0.2510],
        [ 0.7553,  0.3754],
        [ 0.3798,  0.5819],
        [ 0.3922, -0.3195],
        [ 0.0098,  0.3850],
        [ 0.2750,  0.6265],
        [-1.4740, -0.5323]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [21]:
# Constroi a função de perda e otimização 
criterion = nn.MSELoss()

# Otimizador
optimizer = torch.optim.Adam(linear.parameters(), lr=0.01)


In [22]:
#Manda o y para a gpu
y = y.to(device)

# Computa a perda.
loss = criterion(pred, y)
print('Perda: ', loss.item())

# Propaga os erros (backpropagation) e atualiza os pesos
loss.backward()
optimizer.step() # 1-passo do 'gradient descent'

# Imprime a perda depois de 1 passo do gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('Perda depois de 1 passo de otimização : ', loss.item())

#Mais um passo - backpropagation e atualização de pesos
loss.backward()
optimizer.step()

# Imprime a perda depois de 2 passos do gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('Perda depois de 2 passos de otimização : ', loss.item())

Perda:  1.7766430377960205
Perda depois de 1 passo de otimização :  1.736383080482483
Perda depois de 2 passos de otimização :  1.6982431411743164


## Um exemplo mais completo

### Carrega os dados e os separa em treino e teste

In [25]:
import torch
from torch import nn
import torch.nn.functional as F
import pandas as pd
from sklearn.model_selection import train_test_split

device = "cuda" if torch.cuda.is_available() else "cpu"

dfPropaganda = pd.read_csv('Advertising.csv',index_col=0)

y= dfPropaganda.loc[:,'Sales']
X = dfPropaganda.loc[:,['TV','Radio','Newspaper']]

y_tensor = torch.tensor(y.to_numpy())
X_tensor = torch.tensor(X.to_numpy())

X_treino, X_teste, y_treino, y_teste = train_test_split(X_tensor, y_tensor, test_size = 0.30, random_state=5)

print(X_treino.shape)
print(y_treino.shape)

print(X_teste.shape)
print(y_teste.shape)
print(y_teste.ndim)
print(X_treino.dtype)

#Manda para o dispositivo selecionado - no caso, GPU
X_treino = X_treino.float().to(device)
y_treino = y_treino.float().to(device)

#reshape com -1: infere o valor com base no que está sendo passado (passo para sair de 1d e ir para 2d e evitar problemas de cálculos).
y_treino = torch.reshape(y_treino, (-1,1))

X_teste = X_teste.float().to(device)
y_teste = y_teste.float().to(device)
y_teste = torch.reshape(y_teste, (-1,1))

print("\nDepois da conversão para float e do reshape")
print(X_treino.dtype)
print(y_treino.shape)
print(y_teste.shape)
print(y_teste.ndim)

#Já convertemos para float para, pois inicialmente o padrão é double'

torch.Size([140, 3])
torch.Size([140])
torch.Size([60, 3])
torch.Size([60])
1
torch.float64

Depois da conversão para float e do reshape
torch.float32
torch.Size([140, 1])
torch.Size([60, 1])
2


### Implementa uma classe com o modelo

Para definir uma rede neural em PyTorch, criamos uma classe que herda de nn.Module. Definimos as camadas da rede na função __init__ e especificamos como os dados passarão pela rede na função forward. <br>


In [26]:
class Feedforward(torch.nn.Module):
    
        #Esta função é onde você define as camadas totalmente conectadas em sua rede neural
        def __init__(self, input_size, hidden_size):
            super(Feedforward, self).__init__()
            
            
            self.input_size = input_size
            self.hidden_size  = hidden_size
            
            self.fc1 = torch.nn.Linear(self.input_size, self.hidden_size)
            self.fc2 = torch.nn.Linear(self.hidden_size, self.hidden_size)
            self.fc3 = torch.nn.Linear(self.hidden_size, self.hidden_size)
            self.fc4 = torch.nn.Linear(self.hidden_size, 1)
            
        
        #Forward: Especifica como os dados passarão pelo seu modelo
        #x representa nossos dados
        def forward(self, x):
            
            output = self.fc1(x)
            output = F.relu(output)
            
            
            output = self.fc2(output)
            output = F.relu(output)
            
            output = self.fc3(output)
            output = F.relu(output)
            
            output = self.fc4(output)

            return output

### Modelo e critério de otimização
Para acelerar as operações na rede neural, nós a movemos para a GPU, se disponível.

In [27]:
#input = 3 (número de features), e hidden size = 10 (número de neurôneos na camada escondida)
model = Feedforward(3, 10).to(device)
print(model)
criterion = torch.nn.MSELoss()

optimizer = torch.optim.Adam(model.parameters(), lr = 0.001)

Feedforward(
  (fc1): Linear(in_features=3, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=10, bias=True)
  (fc4): Linear(in_features=10, out_features=1, bias=True)
)


### Treino e teste do modelo

In [28]:
model.eval()
print(X_teste.shape)
y_pred = model(X_teste)
antes_treino = criterion(y_pred, y_teste) 
print('Teste - perda antes do treinamento' , antes_treino.item())


#-----------------Treinamento
model.train()
epoch = 1000

for epoch in range(epoch):
    
    #Explicitamente configura os gradientes em zero
    optimizer.zero_grad()
    
    # Passe Forward
    y_pred = model(X_treino)
    
    # Computa a perda
    loss = criterion(y_pred, y_treino)
    
    print('Epoch {}: perda treino: {}'.format(epoch, loss.item()))
    
    # Propaga os erros (backpropagation) e atualiza os pesos
    loss.backward()
    optimizer.step()

    
    
#-----------------Avaliação
model.eval()

y_pred = model(X_teste)
after_train = criterion(y_pred, y_teste) 
print('Teste - perda depois do treinamento' , after_train.item())    


torch.Size([60, 3])
Teste - perda antes do treinamento 155.60873413085938
Epoch 0: perda treino: 157.69883728027344
Epoch 1: perda treino: 155.8976287841797
Epoch 2: perda treino: 154.0786895751953
Epoch 3: perda treino: 152.23849487304688
Epoch 4: perda treino: 150.38320922851562
Epoch 5: perda treino: 148.51319885253906
Epoch 6: perda treino: 146.61959838867188
Epoch 7: perda treino: 144.70167541503906
Epoch 8: perda treino: 142.7581787109375
Epoch 9: perda treino: 140.7838897705078
Epoch 10: perda treino: 138.77272033691406
Epoch 11: perda treino: 136.72340393066406
Epoch 12: perda treino: 134.6379852294922
Epoch 13: perda treino: 132.50711059570312
Epoch 14: perda treino: 130.315185546875
Epoch 15: perda treino: 128.07656860351562
Epoch 16: perda treino: 125.79478454589844
Epoch 17: perda treino: 123.47176361083984
Epoch 18: perda treino: 121.1032943725586
Epoch 19: perda treino: 118.68019104003906
Epoch 20: perda treino: 116.20672607421875
Epoch 21: perda treino: 113.6837921142578

Epoch 273: perda treino: 3.1822257041931152
Epoch 274: perda treino: 3.173130989074707
Epoch 275: perda treino: 3.1640374660491943
Epoch 276: perda treino: 3.154911994934082
Epoch 277: perda treino: 3.1456820964813232
Epoch 278: perda treino: 3.1365904808044434
Epoch 279: perda treino: 3.1276931762695312
Epoch 280: perda treino: 3.118725061416626
Epoch 281: perda treino: 3.1096863746643066
Epoch 282: perda treino: 3.1006109714508057
Epoch 283: perda treino: 3.0915544033050537
Epoch 284: perda treino: 3.0825910568237305
Epoch 285: perda treino: 3.073632001876831
Epoch 286: perda treino: 3.0646326541900635
Epoch 287: perda treino: 3.055626392364502
Epoch 288: perda treino: 3.046830177307129
Epoch 289: perda treino: 3.0381155014038086
Epoch 290: perda treino: 3.029484272003174
Epoch 291: perda treino: 3.0209133625030518
Epoch 292: perda treino: 3.0123660564422607
Epoch 293: perda treino: 3.0038225650787354
Epoch 294: perda treino: 2.9952423572540283
Epoch 295: perda treino: 2.986666440963

Epoch 565: perda treino: 2.097919225692749
Epoch 566: perda treino: 2.0961031913757324
Epoch 567: perda treino: 2.0943236351013184
Epoch 568: perda treino: 2.092496156692505
Epoch 569: perda treino: 2.090869188308716
Epoch 570: perda treino: 2.089041233062744
Epoch 571: perda treino: 2.087235927581787
Epoch 572: perda treino: 2.085557222366333
Epoch 573: perda treino: 2.083632469177246
Epoch 574: perda treino: 2.081890821456909
Epoch 575: perda treino: 2.080144166946411
Epoch 576: perda treino: 2.0783824920654297
Epoch 577: perda treino: 2.076580047607422
Epoch 578: perda treino: 2.07479190826416
Epoch 579: perda treino: 2.0730180740356445
Epoch 580: perda treino: 2.071247100830078
Epoch 581: perda treino: 2.0694353580474854
Epoch 582: perda treino: 2.0677032470703125
Epoch 583: perda treino: 2.0658998489379883
Epoch 584: perda treino: 2.0643577575683594
Epoch 585: perda treino: 2.062440872192383
Epoch 586: perda treino: 2.060696840286255
Epoch 587: perda treino: 2.058997631072998
Epoc

Epoch 849: perda treino: 1.5548489093780518
Epoch 850: perda treino: 1.5524042844772339
Epoch 851: perda treino: 1.5505642890930176
Epoch 852: perda treino: 1.54849374294281
Epoch 853: perda treino: 1.5461033582687378
Epoch 854: perda treino: 1.544543743133545
Epoch 855: perda treino: 1.542296051979065
Epoch 856: perda treino: 1.5400575399398804
Epoch 857: perda treino: 1.538207769393921
Epoch 858: perda treino: 1.5358186960220337
Epoch 859: perda treino: 1.5337845087051392
Epoch 860: perda treino: 1.5317012071609497
Epoch 861: perda treino: 1.5295473337173462
Epoch 862: perda treino: 1.5274298191070557
Epoch 863: perda treino: 1.5253798961639404
Epoch 864: perda treino: 1.5232614278793335
Epoch 865: perda treino: 1.5211340188980103
Epoch 866: perda treino: 1.5191247463226318
Epoch 867: perda treino: 1.5170037746429443
Epoch 868: perda treino: 1.515082836151123
Epoch 869: perda treino: 1.5128681659698486
Epoch 870: perda treino: 1.5109831094741821
Epoch 871: perda treino: 1.50868678092